### ISSUE TITLE
fails with what looks like a python 2 v. python 3 exception syntax issue?

### ISSUE THREAD

**Issue by jrwren** [cmars/juju-relation-mongodb#1]
2016-02-05 19:35:22 INFO juju-log Reactive main running for hook install
2016-02-05 19:35:22 INFO install Traceback (most recent call last):
2016-02-05 19:35:22 INFO install   File "/var/lib/juju/agents/unit-parse-server-0/charm/hooks/inst
all", line 18, in <module>
2016-02-05 19:35:22 INFO install     main()
2016-02-05 19:35:22 INFO install   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/__
init__.py", line 65, in main
2016-02-05 19:35:22 INFO install     bus.discover()
2016-02-05 19:35:22 INFO install   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bu
s.py", line 429, in discover
2016-02-05 19:35:22 INFO install     _register_handlers_from_file(filepath)
2016-02-05 19:35:22 INFO install   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bu
s.py", line 448, in _register_handlers_from_file
2016-02-05 19:35:22 INFO install     _load_module(filepath)
2016-02-05 19:35:22 INFO install   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bu
s.py", line 442, in _load_module
2016-02-05 19:35:22 INFO install     sys.modules[modname] = load_source(modname, realpath)
2016-02-05 19:35:22 INFO install   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bu
s.py", line 35, in load_source
2016-02-05 19:35:22 INFO install     return SourceFileLoader(modname, realpath).load_module()
2016-02-05 19:35:22 INFO install   File "<frozen importlib._bootstrap>", line 539, in _check_name_
wrapper
2016-02-05 19:35:22 INFO install   File "<frozen importlib._bootstrap>", line 1614, in load_module
2016-02-05 19:35:22 INFO install   File "<frozen importlib._bootstrap>", line 596, in _load_module
_shim
2016-02-05 19:35:22 INFO install   File "<frozen importlib._bootstrap>", line 1220, in load
2016-02-05 19:35:22 INFO install   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
2016-02-05 19:35:22 INFO install   File "<frozen importlib._bootstrap>", line 1129, in _exec
2016-02-05 19:35:22 INFO install   File "<frozen importlib._bootstrap>", line 1467, in exec_module
2016-02-05 19:35:22 INFO install   File "<frozen importlib._bootstrap>", line 1572, in get_code
2016-02-05 19:35:22 INFO install   File "<frozen importlib._bootstrap>", line 1532, in source_to_code
2016-02-05 19:35:22 INFO install   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
2016-02-05 19:35:22 INFO install   File "/var/lib/juju/agents/unit-parse-server-0/charm/hooks/relations/mongodb/actions-use-local-charmhelpers/actions/backup.py", line 37
2016-02-05 19:35:22 INFO install     except OSError, e:
2016-02-05 19:35:22 INFO install                   ^
2016-02-05 19:35:22 INFO install SyntaxError: invalid syntax
2016-02-05 19:35:22 ERROR juju.worker.uniter.operation runhook.go:107 hook "install" failed: exit status 1

**Comment by cmars** [comment]
actions/backup.py isn't part of this layer. Reactive charms are required to use python3.

**Comment by jrwren** [comment]
Yes, something is VERY wrong with `charm build` on my machine, in multiple virtual envs even! 

sorry about this, `not-an-issue`.
